all:
  children:
    main:
      hosts:
        192.168.56.10:
          ansible_become: true
          ansible_become_method: sudo
          ansible_become_user: root
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
    replica:
      hosts:
        192.168.56.20:
          ansible_become: true
          ansible_become_method: sudo
          ansible_become_user: root
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
