# -*- mode: ruby -*-
# vi: set ft=ruby :

vms = {
  'main' => {'memory' => '512', 'cpus' => 1, 'ip' => '10', 'box' => 'debian/buster64'},
  'replica' => {'memory' => '512', 'cpus' => 1, 'ip' => '20', 'box' => 'debian/buster64'},
}

Vagrant.configure("2") do |config|

  config.vm.box_check_update = false

  vms.each do |name, conf|
    config.vm.define "#{name}" do |k|
      k.vm.box = "#{conf['box']}"
      k.vm.network 'private_network', ip: "192.168.56.#{conf['ip']}"
      k.vm.hostname = "dns.duquepotato"
      k.vm.provider 'virtualbox' do |vb|
        vb.memory = conf['memory']
        vb.cpus = conf['cpus']
        vb.name = "#{name}"
      end
    config.vm.provision 'shell', inline: <<-SHELL
        sudo apt-get update & apt-get upgrade -y
        sudo apt-get install -y vim net-tools curl git python3
        mkdir -p /root/.ssh
        cp /vagrant/files/key/* /root/.ssh
        chmod 400 /root/.ssh/*
        cp /vagrant/files/key/*.pub /root/.ssh/authorized_keys
    SHELL
    end
  end
end

